services:
  cabinet-rest:
    image: ghcr.io/alf73x/cabinet-rest:${IMAGE_TAG:-latest}

    container_name: cabinet-rest

    restart: always

    ports:
      - "127.0.0.1:8082:8082"

    environment:
      CS_CONFIG_PATH: /app/config/local.yaml
      STORAGE_PATH: /app/storage/cabinet.db

    volumes:
      - ./storage:/app/storage
      - ./config/local.yaml:/app/config/local.yaml:ro