services:
  cabinet-rest:
    build: .
    container_name: cabinet-rest
    restart: always
    ports:
      - "8082:8082"
    environment:
      CS_CONFIG_PATH: /app/config/local.yaml
      STORAGE_PATH: /app/storage/ecabinet.db
      SQLITE_KEY: ${SQLITE_KEY}
    volumes:
      - ./storage:/app/storage