services:
  cabinet-rest:
    build: .
    container_name: cabinet-rest
    restart: always
    ports:
       - "127.0.0.1:8082:8082"
    environment:
      CS_CONFIG_PATH: /app/config/local.yaml
      STORAGE_PATH: /app/storage/cabinet.db
    volumes:
      - ./storage:/app/storage