env: "prod" # local, dev, prod
http_server:
  address: "0.0.0.0:8082" # "localhost:8082"
  read_timeout: 60s # read request 
  write_timeout: 60s  # send answer
  idle_timeout: 60s # connection with client 
jwt:
  secret: "change-me"
  ttl: 720h # 30 × 24 = 720 hours