env: "prod" # local, dev, prod
http_server:
  address: "0.0.0.0:8082" # "localhost:8082"
  timeout: 4s # read request and also send answer
  idle_timeout: 60s # connection with client 
  user: "myuser"
  password: "mypass"
